connections {
  epdg-ike {
    version = 2
    local_addrs = 192.168.216.133
    remote_addrs = %any
    proposals = aes128-sha1-modp2048,aes128-sha1-modp1024,aes256-sha256-modp2048
    pools = ue_pool
    send_cert = always

    local {
      auth = pubkey
      id = ims
      certs = epdg.crt
    }

    remote {
      auth = eap-dynamic
      eap_id = 0001010000000001@nai.epc.mnc001.mcc001.3gppnetwork.org
    }

    children {
      ue-default {
        local_ts = 0.0.0.0/0
        remote_ts = dynamic
        esp_proposals = aes128-sha1,aes256-sha256
        start_action = trap
      }
    }
  }
}

pools {
  ue_pool {
    addrs = 10.46.0.100-10.46.0.200
    dns = 8.8.8.8
  }
}
