eap-radius {
    load = yes
    nas_identifier = strongSwan

    servers {
        local-bridge {
            address = 127.0.0.1
            port = 18120
            secret = pyhss-radius-secret
        }
    }
}
