node_id: epdg.local.std
http:
  listen: ":19092"
ipsec:
  backend: swanctl
  mode: passive
  swanctl_bin: /usr/sbin/swanctl
  connection_name: epdg-ike
  child_prefix: ue
  child_name: ue-default
aaa:
  backend: swm_diameter_eap
  origin_host: epdg.localdomain
  origin_realm: localdomain
  destination_host: swm-handler.localdomain
  destination_realm: localdomain
  eap_provider: nak_only
  eap_max_rounds: 4
protocol:
  plmn:
    mcc: "001"
    mnc: "01"
  swu:
    local_address: 192.168.216.133
    ike_port: 500
    natt_port: 4500
  swm:
    peer_host: 127.0.0.1
    realm: localdomain
    port: 13868
  s2b:
    backend: gtpv2_echo
    pgw_address: 127.0.0.4
    gtpv2_port: 2123
