package lab

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// renderEnv writes deploy/.env, which is how docker-compose learns the static
// addresses, ports and credentials.
func (r *Renderer) renderEnv() error {
	lab := r.Lab
	var b strings.Builder
	b.WriteString("# Generated by `labctl render` from deploy/lab.yaml. Do not edit.\n")
	b.WriteString("# docker-compose reads this file for the bridge addresses and ports.\n\n")
	fmt.Fprintf(&b, "LAB_SUBNET=%s\n", lab.Network.Subnet)
	b.WriteString("LAB_HOST_ADDRESS=" + lab.Network.HostAddress + "\n")
	for _, node := range sortedKeys(lab.Network.Nodes) {
		fmt.Fprintf(&b, "IP_%s=%s\n", strings.ToUpper(node), lab.Network.Nodes[node])
	}
	fmt.Fprintf(&b, "\nPLMN_MCC=%s\nPLMN_MNC=%s\nPLMN_MNC3=%s\nPLMN_REALM=%s\n",
		lab.PLMN.MCC, lab.PLMN.MNC, lab.PLMN.MNC3, lab.PLMN.Realm())
	fmt.Fprintf(&b, "\nKAMAILIO_DB_PASSWORD=%s\nRADIUS_SECRET=%s\n",
		lab.Credentials.KamailioDBPassword, lab.Credentials.RadiusSecret)
	fmt.Fprintf(&b, "IMSI=%s\nKI=%s\nOPC=%s\n",
		lab.Credentials.IMSI, lab.Credentials.KI, lab.Credentials.OPC)
	fmt.Fprintf(&b, "\nEPDG_HTTP_PORT=%d\nEPDG_RADIUS_PORT=%d\nEPDG_IKE_PORT=%d\nEPDG_NATT_PORT=%d\n",
		portOf(lab.EPDG.HTTP.Listen, 19090), portOf(lab.EPDG.RADIUS.Listen, 18120),
		orDefault(lab.EPDG.Protocol.SWu.IKEPort, 500), orDefault(lab.EPDG.Protocol.SWu.NATTPort, 4500))
	fmt.Fprintf(&b, "OPEN5GS_GTPC_PORT=%d\nOPEN5GS_PFCP_PORT=%d\n",
		orDefault(lab.Open5GS.GTPCPort, 2123), orDefault(lab.Open5GS.PFCPPort, 8805))
	fmt.Fprintf(&b, "\n# Profiles drive which optional services docker-compose starts.\n")
	fmt.Fprintf(&b, "COMPOSE_PROFILES=%s\n", strings.Join(r.profiles(), ","))

	path := filepath.Join(r.DeployDir, ".env")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("render: cannot write %s: %w", path, err)
	}
	return nil
}

// profiles decides which compose profiles are active from the lab definition.
func (r *Renderer) profiles() []string {
	profiles := []string{"core"}
	if r.Lab.Open5GS.Enabled {
		profiles = append(profiles, "epc")
	}
	if r.Lab.Open5GS.Enabled && r.Lab.Open5GS.HSSBackend == "open5gs" {
		profiles = append(profiles, "open5gs-hss")
	}
	if r.Lab.ENB.Enabled {
		profiles = append(profiles, "enb")
	}
	return profiles
}

// epdgTemplateData exposes the lookups the ePDG template needs.
type epdgTemplateData struct {
	Lab   *Lab
	PyHSS string
}

// IP resolves a node name to its address. Templates can call methods but not
// call a function held in a field, which is why this is a method.
func (d epdgTemplateData) IP(name string) string { return d.Lab.Network.Node(name) }

// renderEPDG writes the ePDG control plane configuration. It is generated from
// the lab definition rather than copied, because every value in it is a lab
// parameter.
func (r *Renderer) renderEPDG() error {
	lab := r.Lab
	data := epdgTemplateData{lab, fmt.Sprintf("http://%s:8080", lab.Network.Node("pyhss"))}
	const body = `# Generated by labctl from deploy/lab.yaml. Edit deploy/lab.yaml instead.
node_id: {{ .Lab.EPDG.NodeID }}
http:
  listen: "{{ .Lab.EPDG.HTTP.Listen }}"
ipsec:
  backend: {{ .Lab.EPDG.IPSec.Backend }}
  mode: {{ .Lab.EPDG.IPSec.Mode }}
  socket: {{ .Lab.EPDG.IPSec.Socket }}
  connection_name: {{ .Lab.EPDG.IPSec.ConnectionName }}
  child_name: {{ .Lab.EPDG.IPSec.ChildName }}
  timeout_seconds: 5
aaa:
  backend: {{ .Lab.EPDG.AAA.Backend }}
  origin_host: {{ .Lab.EPDG.AAA.OriginHost }}
  origin_realm: {{ .Lab.EPDG.AAA.OriginRealm }}
  destination_host: {{ .Lab.EPDG.AAA.DestinationHost }}
  destination_realm: {{ .Lab.EPDG.AAA.DestinationRealm }}
  eap_max_rounds: {{ .Lab.EPDG.AAA.EAPMaxRounds }}
  pyhss_api:
    base_url: {{ .PyHSS }}
    vector_path_template: /auc/aka/vector_count/1/imsi/{imsi}
    swm_path_template: /auc/swm/eap_aka/plmn/{plmn}/imsi/{imsi}
    oam_ping_path: /oam/ping
    timeout_seconds: 5
radius:
  backend: {{ .Lab.EPDG.RADIUS.Backend }}
  listen: {{ .Lab.EPDG.RADIUS.Listen }}
  secret: {{ .Lab.Credentials.RadiusSecret }}
  realm: {{ .Lab.EPDG.AAA.OriginRealm }}
  require_message_authenticator: true
protocol:
  plmn:
    mcc: "{{ .Lab.PLMN.MCC }}"
    mnc: "{{ .Lab.PLMN.MNC }}"
  swu:
    local_address: {{ .Lab.EPDG.Protocol.SWu.LocalAddress }}
    ike_port: {{ .Lab.EPDG.Protocol.SWu.IKEPort }}
    natt_port: {{ .Lab.EPDG.Protocol.SWu.NATTPort }}
  swm:
    peer_host: {{ .IP "pyhss" }}
    realm: {{ .Lab.EPDG.AAA.OriginRealm }}
    port: 3868
  s2b:
    backend: {{ .Lab.EPDG.Protocol.S2b.Backend }}
    pgw_address: {{ .IP "smf" }}
    gtpv2_port: 2123
    local_address: {{ .Lab.EPDG.Protocol.S2b.LocalAddress }}
    apn: {{ .Lab.EPDG.Protocol.S2b.APN }}
    timeout_seconds: {{ .Lab.EPDG.Protocol.S2b.TimeoutSeconds }}
`
	return r.write("epdg/epdg.yaml", body, data)
}

// renderENB writes an srsRAN 4G enb.conf.
func (r *Renderer) renderENB() error {
	if !r.Lab.ENB.Enabled {
		return nil
	}
	lab := r.Lab
	data := struct {
		Lab *Lab
		MME string
	}{lab, lab.Network.Node("mme")}
	const body = `# Generated by labctl from deploy/lab.yaml. Edit deploy/lab.yaml instead.
# srsRAN 4G enb.conf
[enb]
enb_id = {{ .Lab.ENB.ENBID }}
mcc = {{ .Lab.ENB.MCC }}
mnc = {{ .Lab.ENB.MNC }}
tac = {{ .Lab.ENB.TAC }}
mme_addr = {{ .MME }}
gTP_bind_addr = {{ .Lab.ENB.GTPBindAddress }}
s1c_bind_addr = {{ .Lab.ENB.S1CBindAddress }}
s1c_bind_port = 0
n_prb = {{ .Lab.ENB.NPRB }}

[rf]
dl_earfcn = {{ .Lab.ENB.DLEARFCN }}
tx_gain = {{ .Lab.ENB.TXGain }}
rx_gain = {{ .Lab.ENB.RXGain }}
device_name = {{ .Lab.ENB.Device.Name }}
device_args = {{ .Lab.ENB.Device.Args }}
time_adv_nsamples = auto

[expert]
cipher_algo_pref = {{ join ", " .Lab.ENB.CipherAlgoPref }}
integ_algo_pref = {{ join ", " .Lab.ENB.IntegAlgoPref }}
`
	return r.write("enb/enb.conf", body, data)
}

// renderMariaDB writes the init SQL that creates the CSCF database accounts.
//
// MariaDB only runs /docker-entrypoint-initdb.d on a brand new data directory,
// so this file is generated from lab.yaml rather than duplicated under
// deploy/docker: the password here always matches the one labctl writes into
// the Kamailio DB_URL. Changing credentials still needs a volume reset
// (`make clean`), because an existing data directory is never re-initialised.
func (r *Renderer) renderMariaDB() error {
	password := r.Lab.Credentials.KamailioDBPassword
	body := fmt.Sprintf(`-- Generated by labctl from deploy/lab.yaml.
-- Runs once, when MariaDB first initialises its data directory.
-- Each CSCF connects with its own account, which is what the Kamailio
-- configurations under configs/kamailio expect.
CREATE USER IF NOT EXISTS 'pcscf'@'%%' IDENTIFIED BY '%[1]s';
CREATE USER IF NOT EXISTS 'icscf'@'%%' IDENTIFIED BY '%[1]s';
CREATE USER IF NOT EXISTS 'scscf'@'%%' IDENTIFIED BY '%[1]s';
GRANT ALL PRIVILEGES ON pcscf.* TO 'pcscf'@'%%';
GRANT ALL PRIVILEGES ON icscf.* TO 'icscf'@'%%';
GRANT ALL PRIVILEGES ON scscf.* TO 'scscf'@'%%';
FLUSH PRIVILEGES;
`, password)
	return r.write("mariadb/init.sql", body, nil)
}

// renderPyHSS writes the PyHSS configuration and the provisioning seed.
func (r *Renderer) renderPyHSS() error {
	lab := r.Lab
	subs := [][2]string{
		{`bind_ip: ["127.0.0.8"]`, fmt.Sprintf(`bind_ip: ["%s"]`, lab.Network.Node("pyhss"))},
		{`  host: localhost`, fmt.Sprintf(`  host: %s`, lab.Network.Node("redis"))},
		{`    - 'sip:127.0.0.1:5062'`, fmt.Sprintf(`    - 'sip:%s:5062'`, lab.Network.Node("scscf"))},
		{`  MNC: "01"`, fmt.Sprintf(`  MNC: "%s"`, lab.PLMN.MNC)},
		{`  MCC: "001"`, fmt.Sprintf(`  MCC: "%s"`, lab.PLMN.MCC)},
	}
	if err := r.copyAndSubstitute("configs/pyhss/config.yaml", "pyhss/config.yaml", subs); err != nil {
		return err
	}
	// The subscriber the lab provisions, applied to the SQLite volume on start.
	//
	// These are upserts rather than plain inserts because the image ships a
	// database that already contains this subscriber: changing the credentials
	// in deploy/lab.yaml has to update the existing rows. Every NOT NULL column
	// is supplied, since an INSERT OR REPLACE that omits one is rejected.
	seed := fmt.Sprintf(`-- Generated by labctl from deploy/lab.yaml.
-- Applied to the PyHSS SQLite database on container start.

INSERT INTO auc (auc_id, ki, opc, amf, sqn, imsi, algo)
VALUES (1, '%[1]s', '%[2]s', '8000', 13599, '%[3]s', '3')
ON CONFLICT(auc_id) DO UPDATE SET
  ki = excluded.ki, opc = excluded.opc, amf = excluded.amf, imsi = excluded.imsi, algo = excluded.algo;

INSERT INTO subscriber (subscriber_id, imsi, enabled, auc_id, default_apn, apn_list, msisdn)
VALUES (1, '%[3]s', 1, 1, 1, '1', '123456789')
ON CONFLICT(subscriber_id) DO UPDATE SET
  imsi = excluded.imsi, enabled = excluded.enabled, auc_id = excluded.auc_id,
  default_apn = excluded.default_apn, apn_list = excluded.apn_list;

INSERT INTO apn (apn_id, apn, ip_version, pgw_address, sgw_address,
                 charging_characteristics, apn_ambr_dl, apn_ambr_ul, qci, arp_priority)
VALUES (1, 'ims', 0, '%[4]s', '%[5]s', '0800', 9999999, 9999999, 9, 1)
ON CONFLICT(apn_id) DO UPDATE SET
  apn = excluded.apn, pgw_address = excluded.pgw_address, sgw_address = excluded.sgw_address;

INSERT INTO ims_subscriber (ims_subscriber_id, msisdn, msisdn_list, imsi, ifc_path,
                            scscf, scscf_realm, scscf_peer)
VALUES (1, '123456789', '123456789', '%[3]s', 'default_ifc.xml',
        'sip:%[6]s:5062', 'localdomain', 'scscf.localdomain;hss.localdomain')
ON CONFLICT(ims_subscriber_id) DO UPDATE SET
  imsi = excluded.imsi, scscf = excluded.scscf, scscf_realm = excluded.scscf_realm,
  scscf_peer = excluded.scscf_peer;
`,
		lab.Credentials.KI, lab.Credentials.OPC, lab.Credentials.IMSI,
		lab.Network.Node("upf"), lab.Network.Node("sgwu"),
		lab.Network.Node("scscf"))
	return r.write("pyhss/seed.sql", seed, nil)
}

// kamailioRole describes one CSCF for the address rewrite below.
type kamailioRole struct {
	name     string
	self     string
	ports    []string
	acceptor string
}

// renderKamailio rewrites the three CSCF configurations onto the container
// addresses. The shipped configs are kept as they are; only addresses and paths
// change.
func (r *Renderer) renderKamailio() error {
	lab := r.Lab
	mariadb := lab.Network.Node("mariadb")
	dbPassword := lab.Credentials.KamailioDBPassword
	icscf := lab.Network.Node("icscf")
	scscf := lab.Network.Node("scscf")

	roles := []kamailioRole{
		{name: "pcscf", self: lab.Network.Node("pcscf"), ports: []string{"5060"},
			acceptor: `<Acceptor port="3871" bind="11.22.33.44"/>`},
		{name: "icscf", self: icscf, ports: []string{"5061", "4060"},
			acceptor: `<Acceptor port="3869" bind="127.0.0.1"/>`},
		{name: "scscf", self: scscf, ports: []string{"5062", "6060"},
			acceptor: `<Acceptor port="3870" bind="127.0.0.1"/>`},
	}

	for _, role := range roles {
		subs := [][2]string{
			// Database. The shipped configs point at a local mysqld.
			{fmt.Sprintf("mysql://%s:heslo@127.0.0.1/%s", role.name, role.name),
				fmt.Sprintf("mysql://%s:%s@%s/%s", role.name, dbPassword, mariadb, role.name)},
			// Inter-CSCF routing: the P-CSCF needs the I-CSCF, the I-CSCF the S-CSCF.
			{`sip:127.0.0.1:5061`, fmt.Sprintf("sip:%s:5061", icscf)},
			{`$rd = "127.0.0.1:5062";`, fmt.Sprintf(`$rd = "%s:5062";`, scscf)},
			{`1 sip:127.0.0.1:5062`, fmt.Sprintf("1 sip:%s:5062", scscf)},
			// Listen sockets. The 10.x addresses were the tunnel and IPsec
			// sockets of the single host lab; drop them entirely rather than
			// remapping, otherwise the socket is declared twice on the same
			// address and kamailio rejects the config.
			{"listen=udp:10.255.0.1:5060\n", ""},
			{"listen=udp:10.46.0.1:5060\n", ""},
			// Control and config paths move onto the container layout.
			{`/etc/kamailio_` + role.name, `/etc/kamailio`},
			{`/run/kamailio_` + role.name, `/run/kamailio`},
			// These two are host tuning: they try to pre-fault and wire the whole
			// shared memory pool. In a container the mlock fails, and the
			// registrar save path then dies with SIGSEGV, so leave the pool to
			// grow on demand.
			{`mlock_pages=yes`, `mlock_pages=no`},
			{`shm_force_alloc=yes`, `shm_force_alloc=no`},
		}
		for _, port := range role.ports {
			subs = append(subs,
				[2]string{`listen=udp:127.0.0.1:` + port, fmt.Sprintf("listen=udp:%s:%s", role.self, port)},
				[2]string{`listen=tcp:127.0.0.1:` + port, fmt.Sprintf("listen=tcp:%s:%s", role.self, port)},
			)
		}
		// The Diameter acceptor binds the node address.
		subs = append(subs, [2]string{role.acceptor,
			strings.Replace(strings.Replace(role.acceptor, "11.22.33.44", role.self, 1),
				"127.0.0.1", role.self, 1)})
		// The P-CSCF advertises itself to the I-CSCF; it must be routable.
		subs = append(subs, [2]string{`#!define PCSCF_URL "sip:pcscf.localdomain"`,
			fmt.Sprintf(`#!define PCSCF_URL "sip:%s:5060"`, lab.Network.Node("pcscf"))})

		if err := r.copyTree("configs/kamailio/"+role.name, "kamailio/"+role.name, subs); err != nil {
			return err
		}
	}
	return nil
}

// renderOpen5GS rewrites the EPC configurations and generates the freeDiameter
// peer files the MME and the SMF need in order to reach the HSS.
func (r *Renderer) renderOpen5GS() error {
	if !r.Lab.Open5GS.Enabled {
		return nil
	}
	lab := r.Lab

	// The shipped configs are addressed to the 127.0.0.x layout of the single
	// host lab. Map each of those onto the container that now owns the role.
	legacy := [][2]string{
		{"127.0.0.2", lab.Network.Node("mme")},
		{"127.0.0.3", lab.Network.Node("sgwc")},
		{"127.0.0.4", lab.Network.Node("smf")},
		{"127.0.0.6", lab.Network.Node("sgwu")},
		{"127.0.0.7", lab.Network.Node("upf")},
	}
	if mongo := lab.Network.Node("mongo"); mongo != "" {
		legacy = append(legacy, [2]string{"mongodb://localhost/open5gs",
			fmt.Sprintf("mongodb://%s/open5gs", mongo)})
	}
	if lab.Open5GS.HSSBackend == "open5gs" {
		legacy = append(legacy,
			[2]string{"127.0.0.8", lab.Network.Node("o5gshss")},
			[2]string{"127.0.0.9", lab.Network.Node("o5gpcrf")})
	} else {
		// PyHSS answers both the S6a and the Gx reference points.
		legacy = append(legacy,
			[2]string{"127.0.0.8", lab.Network.Node("pyhss")},
			[2]string{"127.0.0.9", lab.Network.Node("pyhss")})
	}

	// Copy the shipped configs first: not every file mentions every address, so
	// the substitution list is applied per file and non-matches are ignored.
	if err := r.copyTree("configs/open5gs", "open5gs", legacy); err != nil {
		return err
	}
	// The shipped configs also carry parameter values (MME identity, PLMN, the
	// SGW-U address). Those come from lab.yaml, so rewrite them too: the UI edits
	// them and a render has to make the edit real.
	if err := r.applyOpen5GSParameters(); err != nil {
		return err
	}
	// The repository does not ship an SMF/PGW or a UPF config; generate them.
	for _, name := range []string{"smf", "upf"} {
		if _, err := os.Stat(filepath.Join(r.RuntimeDir, "open5gs", name+".yaml")); err == nil {
			continue
		}
		if err := r.write("open5gs/"+name+".yaml", generatedOpen5GSYAML(name), lab); err != nil {
			return err
		}
	}

	// freeDiameter carries S6a from the MME and Gx from the SMF, plus the S6a
	// answer path when Open5GS provides the HSS.
	peer := lab.Network.Node("pyhss")
	if lab.Open5GS.HSSBackend == "open5gs" {
		peer = lab.Network.Node("o5gshss")
	}
	for _, p := range []struct{ name, identity, listen string }{
		{"mme.conf", "mme.localdomain", lab.Network.Node("mme")},
		{"smf.conf", "smf.localdomain", lab.Network.Node("smf")},
	} {
		if err := r.write("freediameter/"+p.name, freeDiameterConf(p.identity, p.listen, peer), nil); err != nil {
			return err
		}
	}
	if lab.Open5GS.HSSBackend == "open5gs" {
		for _, p := range []struct{ name, identity, listen string }{
			{"hss.conf", "hss.localdomain", lab.Network.Node("o5gshss")},
			{"pcrf.conf", "pcrf.localdomain", lab.Network.Node("o5gpcrf")},
		} {
			if err := r.write("freediameter/"+p.name,
				freeDiameterConf(p.identity, p.listen, lab.Network.Node("smf")), nil); err != nil {
				return err
			}
		}
	}
	return nil
}

// applyOpen5GSParameters rewrites the parameter values the UI exposes. The
// left hand side of each pair is the value shipped in configs/open5gs, so a
// change there is caught rather than silently ignored.
func (r *Renderer) applyOpen5GSParameters() error {
	lab := r.Lab
	mme := lab.Open5GS.MME

	mmeSubs := [][2]string{
		{"mme_name: open5gs-mme0", "mme_name: " + mme.MMEName},
		{"mme_gid: 2", fmt.Sprintf("mme_gid: %d", mme.MMEGID)},
		{"mme_code: 1", fmt.Sprintf("mme_code: %d", mme.MMECode)},
		{"      tac: 1", fmt.Sprintf("      tac: %d", mme.TAC)},
		{"    full: Open5GS", "    full: " + mme.NetworkNameFull},
		{"    short: Next", "    short: " + mme.NetworkNameShort},
		{"integrity_order : [ EIA2, EIA1, EIA0 ]",
			fmt.Sprintf("integrity_order : [ %s ]", strings.Join(mme.IntegrityOrder, ", "))},
		{"ciphering_order : [ EEA0, EEA1, EEA2 ]",
			fmt.Sprintf("ciphering_order : [ %s ]", strings.Join(mme.CipheringOrder, ", "))},
		// The PLMN appears twice: GUMMEI and TAI.
		{"        mcc: 001", "        mcc: " + lab.PLMN.MCC},
		{"        mnc: 01", "        mnc: " + lab.PLMN.MNC},
	}
	if err := r.substituteInRuntime("open5gs/mme.yaml", mmeSubs); err != nil {
		return err
	}

	// The SGW-U advertises its GTP-U endpoint to the eNB; the address comes from
	// lab.yaml rather than from the legacy 127.0.0.x mapping.
	sgwuSubs := [][2]string{
		{"      - address: " + lab.Network.Node("sgwu"),
			"      - address: " + lab.Open5GS.SGW.GTPUAddress},
	}
	if err := r.substituteInRuntime("open5gs/sgwu.yaml", sgwuSubs); err != nil {
		return err
	}
	return nil
}

// substituteInRuntime rewrites a file that is already in the runtime tree.
func (r *Renderer) substituteInRuntime(dstRel string, subs [][2]string) error {
	path := filepath.Join(r.RuntimeDir, dstRel)
	body, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("render: cannot read %s: %w", path, err)
	}
	text := string(body)
	for _, sub := range subs {
		if !strings.Contains(text, sub[0]) {
			return fmt.Errorf("render: %s does not contain %q, the shipped config changed", dstRel, sub[0])
		}
		text = strings.ReplaceAll(text, sub[0], sub[1])
	}
	if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
		return fmt.Errorf("render: cannot write %s: %w", path, err)
	}
	return nil
}

// freeDiameterConf renders a freeDiameter peer that talks to one peer over TCP.
// TLS material is required by freeDiameter even for plain TCP peers, so the
// image generates a self-signed certificate at /etc/open5gs/tls.
func freeDiameterConf(identity, listen, peer string) string {
	return fmt.Sprintf(`# Generated by labctl from deploy/lab.yaml.
Identity = "%s";
Realm = "localdomain";
ListenOn = "%s";
TLS_Cred = "/etc/open5gs/tls/diameter.crt", "/etc/open5gs/tls/diameter.key";
TLS_CA = "/etc/open5gs/tls/ca.crt";
NoRelay;
LoadExtension = "/usr/lib/freeDiameter/dict_rfc5777.fdx";
LoadExtension = "/usr/lib/freeDiameter/dict_mip6i.fdx";
LoadExtension = "/usr/lib/freeDiameter/dict_nasreq.fdx";
LoadExtension = "/usr/lib/freeDiameter/dict_nas_mipv6.fdx";
LoadExtension = "/usr/lib/freeDiameter/dict_dcca.fdx";
LoadExtension = "/usr/lib/freeDiameter/dict_dcca_3gpp.fdx";
ConnectPeer = "hss.localdomain" { ConnectTo = "%s"; No_TLS; No_SCTP; };
`, identity, listen, peer)
}

// generatedOpen5GSYAML supplies the components the repository does not ship a
// config for (the SMF/PGW and the UPF).
func generatedOpen5GSYAML(name string) string {
	switch name {
	case "smf":
		return `# Generated by labctl from deploy/lab.yaml.
logger:
  file:
    path: /var/log/open5gs/smf.log
    level: info
global:
  max:
    ue: 1024
smf:
  pfcp:
    server:
      - address: {{ .Network.Node "smf" }}
    client:
      upf:
        - address: {{ .Network.Node "upf" }}
  gtpc:
    server:
      - address: {{ .Network.Node "smf" }}
  gtpu:
    server:
      - address: {{ .Network.Node "smf" }}
  session:
    - subnet: {{ .Open5GS.UEPool.Subnet }}
      gateway: {{ .Open5GS.UEPool.Gateway }}
  dns:
{{- range .Open5GS.DNS }}
    - {{ . }}
{{- end }}
  freeDiameter: /etc/freeDiameter/smf.conf
`
	case "upf":
		return `# Generated by labctl from deploy/lab.yaml.
logger:
  file:
    path: /var/log/open5gs/upf.log
    level: info
global:
  max:
    ue: 1024
upf:
  pfcp:
    server:
      - address: {{ .Network.Node "upf" }}
  gtpu:
    server:
      - address: {{ .Network.Node "upf" }}
  session:
    - subnet: {{ .Open5GS.UEPool.Subnet }}
      gateway: {{ .Open5GS.UEPool.Gateway }}
`
	default:
		return fmt.Sprintf("# Generated by labctl: no configuration is defined for %s.\n", name)
	}
}

// renderStrongSwan rewrites the ePDG's strongSwan configuration. The data plane
// runs in the host network namespace, so it reaches the RADIUS server through
// the host address.
func (r *Renderer) renderStrongSwan() error {
	lab := r.Lab
	subs := [][2]string{
		{"address = 127.0.0.1", fmt.Sprintf("address = %s", lab.Network.HostAddress)},
		{"secret = pyhss-radius-secret", fmt.Sprintf("secret = %s", lab.Credentials.RadiusSecret)},
	}
	return r.copyTree("configs/strongswan", "strongswan", subs)
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func portOf(listen string, fallback int) int {
	if idx := strings.LastIndex(listen, ":"); idx >= 0 {
		if port, err := strconv.Atoi(listen[idx+1:]); err == nil && port > 0 {
			return port
		}
	}
	return fallback
}

func orDefault(v, def int) int {
	if v == 0 {
		return def
	}
	return v
}
