package eap

import (
	"bytes"
	"encoding/hex"
	"testing"
)

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("cannot decode hex %q: %v", s, err)
	}
	return b
}

// The expected values below were produced by an independent implementation of
// RFC 4187 section 7 written directly from the RFC text (see
// test/vectors/gen_vectors.py). Identity, IK and CK are fixed inputs.
const (
	katIdentity = "0001010000000001@nai.epc.mnc001.mcc001.3gppnetwork.org"
	katIK       = "00112233445566778899aabbccddeeff"
	katCK       = "ffeeddccbbaa99887766554433221100"
	katKEncr    = "13d8b8c44cc8e4fa505339abec012ec7"
	katKAut     = "8f50cdc4b26691a354d92ff4f65843c4"
	katMSK      = "561b01f5ce435134075a4c4958f9fabf6706a7a632f4f1577b0a1d4766624899925e7fd033a735cec216d9af8c5d74c5910d174b62597d43225a47d719d61636"
)

func TestDeriveKeysKnownAnswer(t *testing.T) {
	keys, err := DeriveKeys(katIdentity, mustHex(t, katIK), mustHex(t, katCK))
	if err != nil {
		t.Fatalf("DeriveKeys returned an error: %v", err)
	}
	if got, want := hex.EncodeToString(keys.KEncr), katKEncr; got != want {
		t.Errorf("K_encr = %s, want %s", got, want)
	}
	if got, want := hex.EncodeToString(keys.KAut), katKAut; got != want {
		t.Errorf("K_aut = %s, want %s", got, want)
	}
	if got, want := hex.EncodeToString(keys.MSK), katMSK; got != want {
		t.Errorf("MSK = %s, want %s", got, want)
	}
	if len(keys.EMSK) != 64 {
		t.Errorf("EMSK length = %d, want 64", len(keys.EMSK))
	}
	if bytes.Equal(keys.MSK, keys.EMSK) {
		t.Error("MSK and EMSK must be cryptographically separate")
	}
}

func TestDeriveKeysRejectsBadLengths(t *testing.T) {
	if _, err := DeriveKeys(katIdentity, make([]byte, 15), mustHex(t, katCK)); err == nil {
		t.Error("DeriveKeys accepted a 15 octet IK")
	}
	if _, err := DeriveKeys(katIdentity, mustHex(t, katIK), make([]byte, 17)); err == nil {
		t.Error("DeriveKeys accepted a 17 octet CK")
	}
}

func TestBuildChallengeKnownAnswer(t *testing.T) {
	// Expected octets generated by an independent implementation.
	const want = "01070044170100000105000000112233445566778899aabbccddeeff" +
		"0205000011223344556677889900aabbccddeeff" +
		"0b050000a13d851650b84f44bd67d241207a662b"

	rand := mustHex(t, "00112233445566778899aabbccddeeff")
	autn := mustHex(t, "11223344556677889900aabbccddeeff")
	got, err := BuildChallenge(0x07, rand, autn, mustHex(t, katKAut))
	if err != nil {
		t.Fatalf("BuildChallenge returned an error: %v", err)
	}
	if hex.EncodeToString(got) != want {
		t.Fatalf("challenge = %s\nwant        %s", hex.EncodeToString(got), want)
	}

	// The packet must parse as a well formed EAP-Request/AKA-Challenge and its
	// AT_MAC must verify.
	pkt, err := Parse(got)
	if err != nil {
		t.Fatalf("Parse rejected the generated challenge: %v", err)
	}
	if pkt.Code != CodeRequest || pkt.Type != TypeAKA {
		t.Fatalf("unexpected EAP header: code=%s type=%d", pkt.Code, pkt.Type)
	}
	_, _, ok, err := VerifyMAC(got, mustHex(t, katKAut))
	if err != nil {
		t.Fatalf("VerifyMAC returned an error: %v", err)
	}
	if !ok {
		t.Error("AT_MAC of the generated challenge does not verify")
	}

	// A single flipped bit must be detected.
	tampered := append([]byte{}, got...)
	tampered[len(tampered)-1] ^= 0x01
	if _, _, ok, err := VerifyMAC(tampered, mustHex(t, katKAut)); err != nil || ok {
		t.Errorf("VerifyMAC accepted a tampered challenge (ok=%v err=%v)", ok, err)
	}
}

func TestParseResponseRoundTrip(t *testing.T) {
	// EAP-Response/AKA-Challenge carrying AT_RES and AT_MAC.
	res := mustHex(t, "aabbccdd")
	body := []byte{SubtypeChallenge, 0, 0}
	body = append(body, Attribute{Type: ATRES, Value: append([]byte{0, 32}, res...)}.Marshal()...)
	body = append(body, Attribute{Type: ATMAC, Value: make([]byte, 18)}.Marshal()...)
	raw := (&Packet{Code: CodeResponse, Identifier: 0x07, Type: TypeAKA, Data: body}).Marshal()

	off, err := locateMAC(raw)
	if err != nil {
		t.Fatalf("locateMAC: %v", err)
	}
	copy(raw[off:off+16], hmacSHA1Trunc(mustHex(t, katKAut), raw))

	resp, err := ParseResponse(raw)
	if err != nil {
		t.Fatalf("ParseResponse: %v", err)
	}
	if resp.Subtype != SubtypeChallenge {
		t.Errorf("subtype = %d, want %d", resp.Subtype, SubtypeChallenge)
	}
	if !bytes.Equal(resp.RES, res) {
		t.Errorf("RES = %x, want %x", resp.RES, res)
	}
	if _, _, ok, err := VerifyMAC(raw, mustHex(t, katKAut)); err != nil || !ok {
		t.Errorf("AT_MAC did not verify (ok=%v err=%v)", ok, err)
	}
}

func TestParseResponseRejectsBadLength(t *testing.T) {
	// Truncated EAP header declared length.
	raw := []byte{0x02, 0x01, 0x00, 0x40, 0x17, 0x01, 0x00, 0x00}
	if _, err := ParseResponse(raw); err == nil {
		t.Error("ParseResponse accepted a packet whose Length field exceeds the datagram")
	}
}

func TestParseRejectsNonAKA(t *testing.T) {
	raw := (&Packet{Code: CodeResponse, Identifier: 1, Type: TypeMD5Challenge, Data: []byte{16}}).Marshal()
	if _, err := ParseResponse(raw); err == nil {
		t.Error("ParseResponse accepted an EAP-MD5 packet")
	}
}

func TestAttributePadding(t *testing.T) {
	// AT_RES carries a 4 octet RES plus the two reserved octets, so the
	// encoded length must be padded to 12 octets.
	a := Attribute{Type: ATRES, Value: append([]byte{0, 32}, mustHex(t, "aabbccdd")...)}
	enc := a.Marshal()
	if len(enc)%4 != 0 {
		t.Fatalf("encoded AT_RES length %d is not a multiple of four", len(enc))
	}
	if enc[1] != byte(len(enc)/4) {
		t.Fatalf("encoded AT_RES length octet %d does not describe %d octets", enc[1], len(enc))
	}
}
